#alias de la webapp
<VirtualHost *:80>
    ServerName webapp.local
    DocumentRoot /var/www/webapp
    
    <Directory /var/www/webapp>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

#alias de developers
<VirtualHost *:80>
    ServerName developers.local
    DocumentRoot /var/www/developers

    <Directory /var/www/developers>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>